server:
  port: 9915

# API Registry client configuration
eureka:
  instance:
    metadata-map:
      public: false
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
     enabled: false

# Open bank project
openbankproject:
  transactions:
    url: https://apisandbox.openbankproject.com/obp/v1.2.1/banks/rbs/accounts/savings-kids-john/public/transactions

logging:
  level:
    com.backbase.training: DEBUG
